### ISSUE TITLE
 It seems not work in Ubuntu 14.14 64-bit

### ISSUE THREAD

**Issue by CastenettoA** [wakatime/atom-wakatime#49] opened 2016-05-11 08:33 UTC
On windows is all ok, but on ubuntu seem not work.
Console.log

Current wakatime-cli version is 6.0.1
/home/ac-open/.atom/packages/wakatime/lib/wakatime.coffee:304 Checking for updates to wakatime-cli...
/home/ac-open/.atom/packages/wakatime/lib/wakatime.coffee:307 wakatime-cli is up to date

I inserted the API key. 
Installed 2 days ago

**Comment by alanhamlett** [comment] 2016-05-11 11:59
Can you look for error messages in your ~/.wakatime.log file?

Also please turn on debug mode in the `~/.wakatime.cfg` config file:
https://github.com/wakatime/wakatime#troubleshooting

**Comment by CastenettoA** [comment] 2016-05-12 07:35
The file wakatime.log is empty and the file .wakatime.cfg is not in my filesystem.
I tried reinstalling but nothing seems to change

**Comment by alanhamlett** [comment] 2016-05-12 07:50
It looks like we're receiving heartbeats from Atom on Linux under your account now.. did it start working now?

You can check the last time coding activity was received for a plugin here:
https://wakatime.com/api/v1/users/current/user_agents

**Comment by CastenettoA** [comment] 2016-05-12 12:28
It ran for one minute but after no longer worked. Tomorrow I reinstall Atom and let you know
The last time coding axtivity it stops this morning  https://wakatime.com/api/v1/users/current/user_agents

**Comment by gigabyte7ipev** [comment] 2016-05-23 12:01
Same issue for me. Ubuntu 64bits 16.04 + atom. 
 same with brackets

But no ~/.wakatime.log and no ~/.wakatime.cfg in my directory

**Comment by pararang** [comment] 2016-05-26 14:48
Same issue on Ubuntu 14.04 64x. Just migrated from Brackets to Atom two days ago. Now, I've inserted wakatime API but my coding activity is stopping.

**Comment by alanhamlett** [comment] 2016-06-07 10:25
I'm not able to reproduce this in Ubuntu 15.04 64bit, so I need more info. Make sure you have Debug checked in the wakatime settings and you're using at least v6.0.3. Then when you notice it's not logging anymore, check these things:

1. How many windows (not tabs) do you have open? Every window instance of Atom causes the plugin to check for wakatime-cli and re-download it if unable to find the version from GitHub. (v6.0.4 won't update wakatime-cli when unable to connect to GitHub)

2. Do you have any messages in your Atom Developer Console? Make sure you check all open windows, because a message could be in one window's console but not the other.

Also, with debug mode checked you should see every heartbeat being logged to the console as you're typing in files. If you still see heartbeats in your console when saving/changing files then it's still logging.

**Comment by alanhamlett** [comment] 2016-06-08 18:55
I'm thinking this could be related to wakatime/vim-wakatime#39 which was just fixed today. That would cause an unhandled exception that wouldn't output anything to `~/.wakatime.log`. Once everyone auto-updates wakatime-cli to v6.0.4 (which happens every 24 hrs unless Debug is checked) then let's hope it's fixed.

**Closed** 2016-08-20 21:54 UTC
