### ISSUE TITLE
The Latest Update Broke Atom

### ISSUE THREAD

**Issue by austin-thesing** [wakatime/atom-wakatime#57] opened 2016-06-08 20:26 UTC
Atom connection is broken after the latest Atom Package update

**Comment by alanhamlett** [comment] 2016-06-09 09:16
It should be fixed in v6.0.7. Can you update and see if it's working now?

**Comment by alanhamlett** [comment] 2016-06-09 12:35
Closing as duplicate of #58.

**Closed by alanhamlett** 2016-06-09 12:35 UTC
