### ISSUE TITLE
Unknown Error (1); Check your Dev Console and ~/.wakatime.log

### ISSUE THREAD

**Issue by ouatataz** [wakatime/atom-wakatime#114] opened 2021-08-31 20:54 UTC
I use Wakatime in Atom with my API key. In the status bar of Atom, it says 'Error' and on hover, it gives the information as shown in the title.

I'm using Atom 1.58.0 on MacOS Catalina with Wakatime plugin 11.0.4 (no update available).
The ~/.wakatime.log file shows :
`{"caller":"/Users/runner/work/wakatime-cli/wakatime-cli/cmd/legacy/run.go:194","func":"runCmd","level":"error","message":"failed to run command: failed to send heartbeat(s): failed to send heartbeats via api client: failed making request to \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": Post \"https://api.wakatime.com/api/v1/users/current/heartbeats.bulk\": dial tcp 68.183.248.166:443: connect: operation timed out","now":"2021-08-31T22:38:01+02:00","version":"v1.19.0"}`

**Comment by ouatataz** [comment] 2021-09-07 23:39
It looks related to #108 and maybe wakatime/wakatime-cli#432.

**Comment by alanhamlett** [comment] 2021-09-07 23:52
Try restarting Atom and it should get the fixed wakatime-cli.

Fixed with https://github.com/wakatime/wakatime-cli/pull/539.

**Comment by alanhamlett** [comment] 2021-09-07 23:54
Duplicate of #113.

**Closed by alanhamlett** 2021-09-07 23:54 UTC
