### ISSUE TITLE
[plugin] Your Atom plugin is malfunctioning

### ISSUE THREAD

**Issue by dianthedainty** [wakatime/atom-wakatime#118] opened 2021-10-26 20:32 UTC
Here is a reply to the list of Atom extensions you have installed to an existing GitHub issue. I requesting for a reply back. What do I need to do?
Thank you

**Comment by alanhamlett** [comment] 2021-12-18 06:12
Duplicate of #107.

**Closed by alanhamlett** 2021-12-18 06:12 UTC
